##
## Test script for use with VS Code REST Client extension
## 
## Complete these variables with your own values
##

# The endpoint of the deployed function app e.g. https://func-proxy-XXXXXXXX.azurewebsites.net
@endpoint=<ENDPOINT_URL>
# The Web Application which will use the proxy (e.g. http://localhost:3000)
@origin=<ORIGIN_URL>
# The client ID of the application that will use the proxy
@client_id=<CLIENT_ID>
# Existing and new user email addresses for testing
@new_user=<NEW_USERNAME>
@existing_user=<EXISTING_USERNAME>

POST {{endpoint}}/api/signup/v1.0/start HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Origin: {{origin}}

client_id={{client_id}}&username={{new_user}}&challenge_type=oob password redirect
###

POST  {{endpoint}}/api/oauth2/v2.0/initiate HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Origin: {{origin}}}}
X-Size: 100

client_id={{client_id}}&username={{existing_user}}&challenge_type=password redirect
###
