GET http://localhost:7071/api/oauth2/v2.0/token HTTP/1.1
Origin: portal.azure.com
###

OPTIONS http://localhost:7071/api/ HTTP/1.1
Origin: foo.example.com
###

POST http://localhost:7071/api/signup/v1.0/start
Content-Type: application/x-www-form-urlencoded
Origin: foo.example.com

client_id=8156270e-e65f-44e6-afb0-2f0291458a83
&username=jamesc.000@gmail.com
&challenge_type=oob password redirect
###

POST http://localhost:7071/api/oauth2/v2.0/initiate HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Origin: foo.example.com

client_id=8156270e-e65f-44e6-afb0-2f0291458a83&challenge_type=password redirect&username=jamesc.000@gmail.com
###
